coffee/coffee/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('customer.urls')),
    path('payments/', include('paymentsapp.urls')),
    path('owner/', include('owner.urls')),

]

urlpatterns += i18n_patterns (
    path('', include('customer.urls')),
)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

coffee/customer/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



urlpatterns = [
    path('', views.home, name="home"),
    path('register', views.RegisterPage, name="register"),
    path('login', views.LoginPage, name="login"),
    path('logout', views.UserLogout, name="logout"),
    path('shop', views.shop, name="shop"),
    path('blog', views.blog, name="blog"),
    path('contact-us', views.contactus, name="contactus"),
    path('newsletter', views.newsletter, name="newsletter"),
    path('shop-detail/<int:id>/', views.shopdetail, name="shopdetail"),
    path('category-view/<int:id>/', views.categoryview, name="category-view"),
    path('cart', views.cart, name="cart"),
    path('add/<int:id>/', views.add_to_cart, name="add-to-cart"),
    path('remove/<int:id>/', views.cart_remove, name="remove-cart"),
    path('delete/<int:id>/', views.cart_delete, name="delete-cart"),
    path('wishlist', views.wishlist, name="wishlist"),
    path('addwishlist/<int:id>/', views.add_to_wishlist, name="add-wishlist"),
    path('removewishlist/<int:id>/', views.delete_from_wishlist, name="remove-wishlist"),
    path('movecart/<int:id>/', views.move_to_cart, name="move-cart"),
    path('checkout', views.checkout, name="checkout"),
    path('my-orders', views.my_orders, name="my-orders"),
    path('my-profile', views.my_profile, name="my-profile"),
    path("update-profile/<int:id>/",views.UpdateProfile.as_view(), name="update-profile"),
    path("blog-category/<int:id>/",views.blog_category, name="blog_category"),
    path("menu/",views.menu, name="menu"),
    path("services/",views.services, name="services"),
    path("about/",views.about, name="about"),












    

    # Password reset paths
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='forgot_password_reset.html'),name='password_reset'),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='password_reset_complete.html'),name='password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete'),


    



    



   

]
  

coffee/owner/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.dashboard, name="dashboard"),
    path("manage-category",views.ManageCategory, name="manage-category"),
    path("add-category",views.AddCategory, name="add-category"),
    path("update-category/<int:id>/",views.UpdateCategory.as_view(), name="update-category"),
    path("delete-category/<int:id>/",views.DeleteCategory.as_view(), name="delete-category"),
    path("manage-products",views.ManageProducts, name="manage-products"),
    path("add-product",views.AddProduct, name="add-product"),
    path("update-product/<int:id>/",views.UpdateProduct.as_view(), name="update-product"),
    path("delete-product/<int:id>/",views.DeleteProduct.as_view(), name="delete-product"),
    path("manage-blogs",views.ManageBlogs, name="manage-blogs"),
    path("add-blog",views.AddBlog, name="add-blog"),
    path("update-blog/<int:id>/",views.UpdateBlog.as_view(), name="update-blog"),
    path("delete-blog/<int:id>/",views.DeleteBlog.as_view(), name="delete-blog"),
    path("manage-subscribe",views.ManageSubscribe, name="manage-subscribe"),
    path("manage-enquiries",views.ManageEnquiries, name="manage-enquiries"),
    path("view-enquiry/<int:id>/",views.ViewEnquiry, name="view-enquiry"),
    path("manage-orders",views.ManageOrders, name="manage-orders"),


]

coffee/customer/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blogs(models.Model):
    name = models.CharField(max_length=50)
    category = models.CharField(max_length=50)
    image = models.ImageField(upload_to="images/")
    desc = models.CharField(max_length=200)
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

class Contact(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()
    options = (
        ("unread", "unread"),
        ("viewed", "viewed"),
    )
    status = models.CharField(max_length=20, choices=options, default="unread")
    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to="images/")
    desc = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=50)
    featured = models.BooleanField(default=False)
    top_selled = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image_1 = models.ImageField(upload_to="images/")
    image_2 = models.ImageField(upload_to="images/")
    image_3 = models.ImageField(upload_to="images/")
    image_4 = models.ImageField(upload_to="images/")
    price = models.FloatField()
    available = models.BooleanField(default=True)
    desc = models.CharField(max_length=200)
    information = models.TextField()
    width = models.FloatField()
    height = models.FloatField()
    weight = models.FloatField()
    material = models.CharField(max_length=50)
    benefits = models.TextField()
    quality_check = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class NewsLetter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    oredered = models.BooleanField(default=False)


class CartItems(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def sub_total(self):
        return '{}'.format (self.product.price * self.quantity)

    # def __str__(self):
    #     return self.product


class Wishlist(models.Model):
    product= models.ManyToManyField(Products)
    options = (
        ("Wishlisted", "Wishlisted"),
        ("in-cart", "in-cart")
        
    )
    status = models.CharField(max_length=300, choices=options, default="Wishlisted")
    user=models.ForeignKey(User,on_delete=models.CASCADE,null=True)


class Review(models.Model):
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField()
    review = models.TextField()
    rating = models.PositiveSmallIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.product} - {self.rating} stars'


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    add_1 = models.CharField(max_length=100)
    add_2 = models.CharField(max_length=100)
    city = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=20)

    def __str__(self):
        return self.first_name

coffee/customer/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import *



# class CreateUserForm(UserCreationForm):
#     class Meta:
#         model = User
#         fields = ['username', 'email', 'password1', 'password2']


class CreateUserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email address is already in use. Please use a different email address.")


class UpdateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'phone', 'email', 'add_1', 'add_2', 'city', 'country', 'zip_code']

coffee/customer/templates/blog.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %} Home {% endblock %}
{% block body %}

    <section class="home-slider owl-carousel">

      <div class="slider-item" style="background-image: url({% static 'images/bg_3.jpg' %});" data-stellar-background-ratio="0.5">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">

            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">Blog</h1>
	            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Blog</span></p>
            </div>

          </div>
        </div>
      </div>
    </section>

    <section class="ftco-section">
      <div class="container">
        <div class="row d-flex">
          <div class="col-md-4 d-flex ftco-animate">
          	<div class="blog-entry align-self-stretch">
              <a href="blog-single.html" class="block-20" style="background-image: url({% static 'images/image_1.jpg' %});">
              </a>
              <div class="text py-4 d-block">
              	<div class="meta">
                  <div><a href="#">Sept 28, 2018</a></div>
                  <div><a href="#">Admin</a></div>
                  <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
                </div>
                <h3 class="heading mt-2"><a href="#">Coffee Testing Day</a></h3>
                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
              </div>
            </div>
          </div>
          <div class="col-md-4 d-flex ftco-animate">
          	<div class="blog-entry align-self-stretch">
              <a href="blog-single.html" class="block-20" style="background-image: url({% static 'images/image_2.jpg' %});">
              </a>
              <div class="text py-4 d-block">
              	<div class="meta">
                  <div><a href="#">Sept 28, 2018</a></div>
                  <div><a href="#">Admin</a></div>
                  <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
                </div>
                <h3 class="heading mt-2"><a href="#">Coffee Testing Day</a></h3>
                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
              </div>
            </div>
          </div>
          <div class="col-md-4 d-flex ftco-animate">
          	<div class="blog-entry align-self-stretch">
              <a href="blog-single.html" class="block-20" style="background-image: url({% static 'images/image_3.jpg' %});">
              </a>
              <div class="text py-4 d-block">
              	<div class="meta">
                  <div><a href="#">Sept 28, 2018</a></div>
                  <div><a href="#">Admin</a></div>
                  <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
                </div>
                <h3 class="heading mt-2"><a href="#">Coffee Testing Day</a></h3>
                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
              </div>
            </div>
          </div>
          <div class="col-md-4 d-flex ftco-animate">
          	<div class="blog-entry align-self-stretch">
              <a href="blog-single.html" class="block-20" style="background-image: url({% static 'images/image_4.jpg' %});">
              </a>
              <div class="text py-4 d-block">
              	<div class="meta">
                  <div><a href="#">Sept 28, 2018</a></div>
                  <div><a href="#">Admin</a></div>
                  <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
                </div>
                <h3 class="heading mt-2"><a href="#">Coffee Testing Day</a></h3>
                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
              </div>
            </div>
          </div>
          <div class="col-md-4 d-flex ftco-animate">
          	<div class="blog-entry align-self-stretch">
              <a href="blog-single.html" class="block-20" style="background-image: url({% static 'images/image_5.jpg' %});">
              </a>
              <div class="text py-4 d-block">
              	<div class="meta">
                  <div><a href="#">Sept 28, 2018</a></div>
                  <div><a href="#">Admin</a></div>
                  <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
                </div>
                <h3 class="heading mt-2"><a href="#">Coffee Testing Day</a></h3>
                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
              </div>
            </div>
          </div>
          <div class="col-md-4 d-flex ftco-animate">
          	<div class="blog-entry align-self-stretch">
              <a href="blog-single.html" class="block-20" style="background-image: url({% static 'images/image_6.jpg' %});">
              </a>
              <div class="text py-4 d-block">
              	<div class="meta">
                  <div><a href="#">Sept 28, 2018</a></div>
                  <div><a href="#">Admin</a></div>
                  <div><a href="#" class="meta-chat"><span class="icon-chat"></span> 3</a></div>
                </div>
                <h3 class="heading mt-2"><a href="#">Coffee Testing Day</a></h3>
                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
              </div>
            </div>
          </div>
        </div>
        <div class="row mt-5">
          <div class="col text-center">
            <div class="block-27">
              <ul>
                <li><a href="#">&lt;</a></li>
                <li class="active"><span>1</span></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">&gt;</a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </section>

 {% endblock %}

coffee/customer/templates/login.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %} Home {% endblock %}
{% block body %}

    <section class="home-slider owl-carousel">

      <div class="slider-item" style="background-image: url({% static 'images/bg_3.jpg' %});" data-stellar-background-ratio="0.5">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">

            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">{% trans 'Login To continue' %}</h1>
	            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Login</span></p>
            </div>

          </div>
        </div>
      </div>
    </section>



            <form action="#" method="POST">
                 {%csrf_token%}
            	<div class="d-flex flex-row align-items-center mb-4">

              </div>
              <div class="form-group">
                <input type="text" class="form-control" placeholder="{% trans 'Username' %}">
                  <input type="text" name="username" class="form-control" />
              </div>


              <div class="form-group">
                <input type="text" class="form-control" placeholder="{% trans 'Password' %}">
                   <input type="password" name="password" class="form-control" />
              </div>


              <div class="form-group">
                <input type="submit" value="LOGIN" class="btn btn-primary py-3 px-5">



               <a href="{%url 'register'%}" class="btn btn-primary py-3 px-5">{% trans 'SIGN UP' %}</a>
              </div>


                <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                    <a href="{%url 'password_reset' %}" style="color:red;">{% trans 'Forgot password' %}?</a>
                </div>



            </form>
          </div>
        </div>
      </div>
    </section>




 {% endblock %}

coffee/customer/templates/my-orders.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block body %}




    <section class="home-slider owl-carousel">
      <div class="slider-item" style="background-image: url({% static 'images/bg_1.jpg' %});">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">

            <div class="col-md-8 col-sm-12 text-center ftco-animate">
            	<span class="subheading">Welcome</span>
              <h1 class="mb-4">My Orders</h1>
              <p class="mb-4 mb-md-5">A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
            </div>

          </div>
        </div>
      </div>

      <div class="slider-item" style="background-image: url({% static 'images/bg_2.jpg' %});">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">

            <div class="col-md-8 col-sm-12 text-center ftco-animate">
            	<span class="subheading">Welcome</span>
              <h1 class="mb-4">My Orders</h1>
              <p class="mb-4 mb-md-5">A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
            </div>

          </div>
        </div>
      </div>

      <div class="slider-item" style="background-image: url({% static 'images/bg_3.jpg' %});">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center" data-scrollax-parent="true">

            <div class="col-md-8 col-sm-12 text-center ftco-animate">
            	<span class="subheading">Welcome</span>
              <h1 class="mb-4">My Orders</h1>
              <p class="mb-4 mb-md-5">A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
            </div>

          </div>
        </div>
      </div>
    </section>



 {%if orders%}
  <section class="cart_area padding_top">
    <div class="container">
      <div class="cart_inner">
        <div class="table-responsive">
          <table class="table">
            <thead>
              <tr>
                <th scope="col">{% trans 'Product' %}</th>
                <th scope="col">{% trans 'Price' %}</th>
                <th scope="col">{% trans 'Quantity' %}</th>
                <th scope="col">{% trans 'Total' %}</th>
              </tr>
            </thead>
            <tbody>
              {% for cart in orders %}
              {%for item in cart.cartitems_set.all %}
              <tr>
                <td>
                  <div class="media">
                    <div class="d-flex">
                      <img src="{{item.product.image_1.url}}" style="width:50px;height:50px;" alt="" />
                    </div>
                    <div class="media-body">
                      <p>{{item.product.name}}</p>
                    </div>
                  </div>
                </td>
                <td>
                  <h5>${{item.product.price}}</h5>
                </td>
                <td>
                  {{item.quantity}}



                </td>
                <td>
                  <h5>${{item.sub_total }}</h5>
                </td>
              </tr>
              {% endfor %}
              {% endfor %}
              <!-- <tr>
                <td>
                  <div class="media">
                    <div class="d-flex">
                      <img src="img/product/single-product/cart-1.jpg" alt="" />
                    </div>
                    <div class="media-body">
                      <p>Minimalistic shop for multipurpose use</p>
                    </div>
                  </div>
                </td>
                <td>
                  <h5>$360.00</h5>
                </td>
                <td>
                  <div class="product_count"> -->
                    <!-- <input type="text" value="1" min="0" max="10" title="Quantity:"
                      class="input-text qty input-number" />
                    <button
                      class="increase input-number-increment items-count" type="button">
                      <i class="ti-angle-up"></i>
                    </button>
                    <button
                      class="reduced input-number-decrement items-count" type="button">
                      <i class="ti-angle-down"></i>
                    </button> -->
                    <!-- <span class="input-number-decrement"> <i class="ti-angle-down"></i></span>
                    <input class="input-number" type="text" value="1" min="0" max="10">
                    <span class="input-number-increment"> <i class="ti-angle-up"></i></span>
                  </div>
                </td>
                <td>
                  <h5>$720.00</h5>
                </td>
              </tr> -->
              <!-- <tr>
                <td>
                  <div class="media">
                    <div class="d-flex">
                      <img src="img/product/single-product/cart-1.jpg" alt="" />
                    </div>
                    <div class="media-body">
                      <p>Minimalistic shop for multipurpose use</p>
                    </div>
                  </div>
                </td>
                <td>
                  <h5>$360.00</h5>
                </td>
                <td>
                  <div class="product_count">
                    <span class="input-number-decrement"> <i class="ti-angle-down"></i></span>
                    <input class="input-number" type="text" value="1" min="0" max="10">
                    <span class="input-number-increment"> <i class="ti-angle-up"></i></span>
                  </div>
                </td>
                <td>
                  <h5>$720.00</h5>
                </td>
              </tr> -->
              <tr class="bottom_button">
                <td>
                  <!-- <a class="btn_1" href="#">Update Cart</a> -->
                </td>
                <td></td>
                <td></td>
                <td>
                  <div class="cupon_text float-right">
                    <!-- <a class="btn_1" href="#">Close Coupon</a> -->
                  </div>
                </td>
              </tr>
              <tr>
                <td></td>
                <td></td>
                <td>
                  <!-- <h5>Subtotal</h5> -->
                </td>
                <td>
                  <!-- <h5>${{total}}</h5> -->
                </td>
              </tr>
              <tr class="shipping_area">
                <!-- <td></td> -->
                <!-- <td></td> -->
                <!-- <td> -->
                  <!-- <h5>Shipping</h5> -->
                <!-- </td> -->
                <!-- <td> -->
                  <!-- <div class="shipping_box"> -->
                    <!-- <ul class="list">
                      <li>
                        <a href="#">Flat Rate: $5.00</a>
                      </li>
                      <li>
                        <a href="#">Free Shipping</a>
                      </li>
                      <li>
                        <a href="#">Flat Rate: $10.00</a>
                      </li>
                      <li class="active">
                        <a href="#">Local Delivery: $2.00</a>
                      </li>
                    </ul> -->
                    <!-- <h6>
                      Calculate Shipping
                      <i class="fa fa-caret-down" aria-hidden="true"></i>
                    </h6> -->
                    <!-- <select class="shipping_select"> -->
                      <!-- <option value="1">Bangladesh</option>
                      <option value="2">India</option>
                      <option value="4">Pakistan</option> -->
                    <!-- </select> -->
                    <!-- <select class="shipping_select section_bg"> -->
                      <!-- <option value="1">Select a State</option>
                      <option value="2">Select a State</option>
                      <option value="4">Select a State</option>
                    </select> -->
                    <!-- <input type="text" placeholder="Postcode/Zipcode" /> -->
                    <!-- <a class="btn_1" href="#">Update Details</a> -->
                  <!-- </div> -->
                <!-- </td> -->
              </tr>
            </tbody>
          </table>
          <div class="checkout_btn_inner float-right">
            <!-- <a class="btn_1" href="{% url 'shop' %}">Continue Shopping</a> -->
            <!-- <a class="btn_1 checkout_btn_1" href="{% url 'checkout' %}">Proceed to checkout</a> -->
          </div>
        </div>
      </div>
  </section>
  {%else%}
  <div class="container" style="margin-top: 100px;"><center><h3>{% trans 'You dont have made any orders' %}
    !!!!</h3></center>
  <a href="{% url 'shop' %}" style="text-align: center;">{% trans 'Continue shopping' %}
    </a></div>
  {%endif%}




{% endblock %}

coffee/customer/templates/password_reset_complete.html
{%extends 'base.html'%}
{% block title %}Password reset {% endblock %}
{%block body%}
<div class="container">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8">
            <h1><center>Hooray!</center></h1>
            <br>
            <br>
            <p><center>We've emailed you instructions for setting your password.</center></p>
            <p><center>If you don't receive an email, please make sure you've entered the address you registered with, thank you!.</center></p>
        </div>
        <div class="col-2"></div>
    </div>
</div>

{% endblock %}

coffee/customer/templates/register.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% block title %} Home {% endblock %}
{% block body %}

    <section class="home-slider owl-carousel">

      <div class="slider-item" style="background-image: url({% static 'images/bg_3.jpg' %});" data-stellar-background-ratio="0.5">
      	<div class="overlay"></div>
        <div class="container">
          <div class="row slider-text justify-content-center align-items-center">

            <div class="col-md-7 col-sm-12 text-center ftco-animate">
            	<h1 class="mb-3 mt-5 bread">{% trans 'Register with us' %}</h1>
	            <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home</a></span> <span>Registration</span></p>
            </div>

          </div>
        </div>
      </div>
    </section>





                                     <form action="" method="POST">
                                    {%csrf_token%}

                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <!-- <i class="fas fa-user fa-lg me-3 fa-fw"></i> -->
                                        <div class="form-outline flex-fill mb-0">
                                            <label class="form-label" for="form3Example1c">Your Name</label><br>
                                            <input id="username" name="username" type="text" class="form-control">

                                            <!-- <input type="text" id="form3Example1c" class="form-control" /> -->
                                        </div>
                                    </div>

                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <!-- <i class="fas fa-envelope fa-lg me-3 fa-fw"></i> -->
                                        <div class="form-outline flex-fill mb-0">
                                            <label class="form-label" for="form3Example3c">Your Email</label><br>
                                            <input id="email" name="email" type="email" class="form-control">


                                            <!-- <input type="email" id="form3Example3c" class="form-control" /> -->
                                        </div>
                                    </div>

                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <!-- <i class="fas fa-lock fa-lg me-3 fa-fw"></i> -->
                                        <div class="form-outline flex-fill mb-0">
                                            <label class="form-label" for="form3Example4c">Password</label><br>
                                            <input id="password1" name="password1" type="password" class="form-control">


                                            <!-- <input type="password" id="form3Example4c" class="form-control" /> -->
                                        </div>
                                    </div>

                                    <div class="d-flex flex-row align-items-center mb-4">
                                        <!-- <i class="fas fa-key fa-lg me-3 fa-fw"></i> -->
                                        <div class="form-outline flex-fill mb-0">
                                            <label class="form-label" for="form3Example4cd">Repeat your
                                                password</label><br>
                                            <input id="password2" name="password2" type="password" class="form-control">


                                            <!-- <input type="password" id="form3Example4cd" class="form-control" /> -->
                                        </div>
                                    </div>
                                    <br>


                                    <div>
                                        <p>{{form.errors}}</p>
                                    </div>


                                    <div class="d-flex justify-content-center mx-4 mb-3 mb-lg-4">
                                        <input type="submit" value="REGISTER" class="btn_2"></input>&nbsp;&nbsp;
                                        <a href="{% url 'login' %}" class="btn_2">LOGIN</a>
                                    </div>

                                </form>


          </div>
        </div>
      </div>
    </section>




 {% endblock %}